Re-stacking2/config/routes.rb
Rails.application.routes.draw do
  root 'publics/abouts#about'
	devise_for :admins, controllers: {
		sessions: 'admins/sessions',
		passwords: 'admins/passwords',
		registrations: 'admins/registrations'
  	}

	devise_for :users, controllers:{
	    sessions: 'publics/sessions',
	    passwords: 'publics/passwords',
	    registrations: 'publics/registrations'
	}
  namespace :admins do
    resources :results, only: [:index, :update]
  end

  namespace :admins do
    resources :post_comments, only: [:destroy]
  end

  namespace :admins do
    resources :posts, only: [:index, :show, :destroy]
  end

  namespace :admins do
    resources :users, only: [:index, :show]
  end

  scope module: :publics do
    resources :evaluations, only: [:show, :create, :update]
  end

  scope module: :publics do
    resources :schedules, only: [:index, :create]
  end

  scope module: :publics do
    resources :notifications, only: [:index]
  end

 scope module: :publics do
    resources :rewards, only: [:create]
  end

  scope module: :publics do
    resources :posts, only: [:index, :show, :create, :destroy]do
    	resource :post_comments, only: [:create, :destroy]
    	resource :favorites, only: [:create, :destroy]
    end
  end

  scope module: :publics do
    resources :abouts, only: [:index]
    get '/about' => 'abouts#about'
  end

  scope module: :publics do
    resources :users, only: [:show, :update, :destroy]do
      resources :relationships, only: [:create, :destroy]
      get :follows, on: :member
      get :followers, on: :member
    end
  end

  scope module: :publics do
    resources :relationships, only: [:create, :destroy]
  end
end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

Re-stacking2/app/models/user.rb
class User < ApplicationRecord
   # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :profile_image

  has_many :posts, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :schedules, dependent: :destroy
  has_many :rewards, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_stories, through: :favorites, source: :story

  # フォローされる側
  has_many :active_relationships, class_name: "Relationship", foreign_key: :following_id
  has_many :followings, through: :active_relationships, source: :follower

  # フォローする側
  has_many :passive_relationships, class_name: "Relationship", foreign_key: :follower_id
  has_many :followers, through: :passive_relationships, source: :following


  def following?(user)
    active_relationships.find_by(follower_id: user.id)
  end

  def follow(user)
    active_relationships.create(follower_id: user.id)
  end

  def unfollow(user)
    active_relationships.find_by(follower_id: user.id).destroy
  end

  # 通知を送る側
  has_many :active_notifications, class_name: 'Notification', foreign_key: 'visitor_id', dependent: :destroy

  # 通知を送られる側
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy

  def create_notification_follow!(current_user)
    temp = Notification.where(["visitor_id = ? and visited_id = ? and action = ? ",current_user.id, id, 'follow'])
    if temp.blank?
      notification = current_user.active_notifications.new(
        visited_id: id,
        action: 'follow'
      )
      notification.save if notification.valid?
  	end
  end

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :first_name_kana, presence: true
  validates :last_name_kana, presence: true
  validates :nick_name, presence: true
  validates :goal, presence: true
  validates :email, presence: true
  validates :encrypted_password, presence: true
  validates :first_name, length: { maximum: 20 }
  validates :last_name, length: { maximum: 20 }
end

Re-stacking2/app/controllers/admins/users_controller.rb
class Admins::UsersController < Admins::ApplicationController
  def index
  	@users = User.all
  end

  def show
  	@user = User.find(params[:id])
  	@posts = @user.posts.all
  end

  private
  def user_params
  	  params.require(:user).permit(:first_name, :last_name, :first_name_kana, :last_name_kana, :nick_name, :goal, :profile_image, :email)
  end
end

Re-stacking2/app/controllers/publics/abouts_controller.rb
class Publics::AboutsController < ApplicationController
	def about
	end
end

Re-stacking2/app/controllers/publics/application_controller.rb
class Publics::ApplicationController < ApplicationController
end

Re-stacking2/app/controllers/publics/confirmations_controller.rb
# frozen_string_literal: true

class Publics::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

Re-stacking2/app/controllers/publics/evaluations_controller.rb
class Publics::EvaluationsController < ApplicationController
  def show
  end

  def create
  end

  def update
  end
end

Re-stacking2/app/controllers/publics/favorites_controller.rb
class Publics::FavoritesController < Publics::ApplicationController
	before_action :set_variables

  def create
    favorite = current_user.favorites.new(post_id: @post.id)
    favorite.save
    render 'favorite.js.erb'
  end

  def destroy
    favorite = current_user.favorites.find_by(post_id: @post.id)
    favorite.destroy
    render 'favorite.js.erb'
  end

  private

  def set_variables
    @post = Post.find(params[:post_id])
    @id_name = "#favorite-link-#{@post.id}"
  end
end

Re-stacking2/app/controllers/publics/notifications_controller.rb
class Publics::NotificationsController < Publics::ApplicationController
  def index
  end
end

Re-stacking2/app/controllers/publics/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Publics::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

Re-stacking2/app/controllers/publics/passwords_controller.rb
# frozen_string_literal: true

class Publics::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

Re-stacking2/app/controllers/publics/post_comments_controller.rb
class Publics::PostCommentsController < Publics::ApplicationController
  def create
  end
end

Re-stacking2/app/controllers/publics/posts_controller.rb
class Publics::PostsController < Publics::ApplicationController
  def index
    @posts = Post.all
    @post = Post.new
  end

  def show
    @post = Post.find(params[:id])
    @posts = Post.find(params[:id])
  end

  def create
  	@post = Post.new(post_params)
  	@post.user_id = current_user.id
  	if @post.save
      redirect_to posts_path
    end
  end

  def destroy
    @post = Post.find(post_params)
    @post.destroy
    redirect_to posts_path
  end

private
    def post_params
        params.require(:post).permit(:post_content, :post_image)
    end
end

Re-stacking2/app/controllers/publics/registrations_controller.rb
# frozen_string_literal: true

class Publics::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

Re-stacking2/app/controllers/publics/relationships_controller.rb
class Publics::RelationshipsController < Publics::ApplicationController

	def create
	  @user = User.find(params[:follower_id])
	  current_user.follow(@user)
	  respond_to do |format|
	    format.html { redirect_to @user }
	    format.js
	  end
	end

	def destroy
	  @user = Relationship.find(params[:id]).follower
	  current_user.unfollow(@user)
	  respond_to do |format|
	    format.html { redirect_to @user }
	    format.js
	  end
	end

	private
  def relationship_params
  	  params.require(:relationship).permit(:follower_id)
  end
end

Re-stacking2/app/controllers/publics/rewards_controller.rb
class Publics::RewardsController < Publics::ApplicationController
  def create
  end
end

Re-stacking2/app/controllers/publics/schedules_controller.rb
class Publics::SchedulesController < Publics::ApplicationController
  def index
  end

  def create
  end
end

Re-stacking2/app/controllers/publics/sessions_controller.rb
# frozen_string_literal: true

class Publics::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

Re-stacking2/app/controllers/publics/unlocks_controller.rb
# frozen_string_literal: true

class Publics::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

Re-stacking2/app/controllers/publics/users_controller.rb
class Publics::UsersController <  Publics::ApplicationController
  def show
  	  @user = User.find(params[:id])
  	  @posts = @user.posts.all
  	end

  def update
  	@user = User.find(params[:id])
  	  if @user.id == current_user.id
  	  	 @user.update(user_params)
  	  	 redirect_to user_path(current_user)
  	  end
  end

  def destroy
  	@user = User.find(params[:id])
  	@user.destroy
  	redirect_to root_path
  end
  private
  def user_params
  	  params.require(:user).permit(:first_name, :last_name, :first_name_kana, :last_name_kana, :nick_name, :goal, :profile_image, :email)
  end
end

Re-stacking2/app/helpers/admins/users_helper.rb
module Admins::UsersHelper
end

Re-stacking2/app/views/publics/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build, remote: true) do |f| %>
  <%= hidden_field_tag :follower_id, @user.id %>
  <%= f.submit "フォローする" %>
<% end %>

Re-stacking2/app/views/publics/users/_follow_form.html.erb
<% if user_signed_in? && @user != current_user %>
  <div id="follow_form">
    <% if current_user.following?(@user) %>
      <%= render "publics/users/unfollow", users: @user %>
    <% else %>
      <%= render "publics/users/follow", users: @user %>
    <% end %>
  </div>
<% end %>

Re-stacking2/app/views/publics/users/_post.html.erb
<%= render 'publics/favorites/favorite', post: post %>

Re-stacking2/app/views/publics/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(follower_id: @user.id), html: { method: :delete }, remote: true) do |f| %>
  <%= f.submit "フォロー解除" %>
<% end %>

Re-stacking2/app/views/publics/users/show.html.erb
<div class="container">
	<h2>マイページ</h2>
	<div class="row">
		<div class="col">
			<div class="profile1">
				<%= attachment_image_tag @user, :profile_image, :fill, 120, 120, fallback: "no_image.jpg", class: "img-circle pull-left profile-thumb" %>
			</div>
			<div class="profile2">
				<p>
			        <span>名前:</span>
			        <span class="profile_name"><%= @user.first_name %></span>
			        <span class="profile_name"><%= @user.last_name %></span>
		    	</p>
		    	<p>
			        <sapn>フリガナ:</sapn>
			        <span class="profile_name"><%= @user.first_name_kana %></span>
			        <span class="profile_name"><%= @user.last_name_kana %></span>
	   			</p>
	   			<P>
			        <span>ニックネーム:</span>
			        <span class="profile_name"><%= @user.nick_name %></span>
	    		</P>
	    		<p>
		        	<span>目標:</span>
		        	<span class="profile_goal"><%= @user.goal %></span>
	    		</p>
	    		<p>
					<span>メールアドレス:</span>
				　　 <span class="profile_email"><%= @user.email %></span>
				</p>
			</div>
			<div class="edit clearfix">
				<div class="profile-button">
					<button type="button" class="btn btn-primary mt-5" data-toggle="modal" data-target="#edit">プロフィールを編集する</button>
					<p>
				  		<%= link_to "退会する", user_path, class:"btn btn-danger", method: :delete, "data-confirm" => "本当に退会しますか?" %>
				  		<%= render 'publics/users/follow_form', users: @user %>
				  	</p>
			  	</div>
				  <div class="modal fade" id="edit" tabindex="-1" role="dialog" aria-hidden="true">
				    <div class="modal-dialog" role="document">
				      <div class="modal-content">
				        <%= form_with model: @user do |f| %>
				          <div class="modal-body">
				          	<P>
					            <span>画像</span>
					            <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg", class: "img-circle pull-left profile-thumb" %>
								<%= f.attachment_field :profile_image %>
				        	</P>
				            <P>
					            <span>名前</span>
					            <span><%= f.text_field :first_name, class: "form-control" %></span>
					            <span><%= f.text_field :last_name, class: "form-control" %></span>
				        	</P>
				        	<P>
					            <span>フリガナ</span>
					            <span><%= f.text_field :first_name_kana, class: "form-control" %></span>
					            <span><%= f.text_field :last_name_kana, class: "form-control" %></span>
				        	</P>
				        	<P>
					            <span>ニックネーム</span>
					            <span><%= f.text_field :nick_name, class: "form-control" %></span>
				        	</P>
				        	<P>
					            <span>目標</span>
					            <span><%= f.text_field :goal, class: "form-control" %></span>
				        	</P>
				        	<P>
					            <span>メールアドレス</span>
					            <span><%= f.text_field :email, class: "form-control" %></span>
				        	</P>
				          </div>
				          <div class="modal-footer">
				            <button type="button" class="btn btn-secondary" data-dismiss="modal">閉じる</button>
				            <%= f.submit "変更する", class: "btn btn-primary" %>
				          </div>
				        <% end %>
				      </div>
				    </div>
				  </div>
			</div>
			<!-- タブメニューactiveクラスに、クリック済のデザインを設定したcssを指定 -->
			<div class="tab clearfix">
			  <li class="active">投稿</li>
			  <li>コメント</li>
			  <li>いいね</li>
			</div>
			<!-- コンテンツ全体を非表示にし、showクラスが付いたコンテンツのみ表示 -->
			<div class="area">
			  	<ul class="show">
					<% @posts.each do |f| %>
						<div class="posta">
							<div class="col text-center">
								<%= link_to post_path(f.id) do %>
		    						<%= attachment_image_tag f, :post_image, :fill, 500, 500, format: 'jpeg'%></br>
		    					<% end %>
		    				</div>
	    					<i><%= f.post_content %></br><i>
	                        <i>いいね<%= f.favorites.count %></br></i>
	                        <i>コメント <%= f.post_comments.count %></i>
		                </div>
					<% end %>
				</ul>
				<ul>
					<% @posts.each do |f| %>
						<div class="posta">
							<div class="posta">
								<div class="col text-center">
									<%= link_to post_path(f.id) do %>
			    						<%= attachment_image_tag f, :post_image, :fill, 500, 500, format: 'jpeg'%></br>
			    					<% end %>
			    				</div>
		    					<i><%= f.post_content %></br><i>
		                        <i>いいね<%= f.favorites.count %></br></i>
		                        <i>コメント <%= f.post_comments.count %></i>
			                </div>
			            </div>
					<% end %>
				</ul>
				<ul>
				    <li></li>
				    <li></li>
				    <li></li>
				</ul>
			</div>
		</div>
	</div>
</div>